// Automatically generated by the bundler tool from FranklinGothicMedium_14.rdf

#define FranklinGothicMedium_14_NUM_RESOURCES 2UL

#define FranklinGothicMedium_14_Font_OFFSET 0UL
#define FranklinGothicMedium_14_FontData_OFFSET 20UL
