// Automatically generated by the bundler tool from FranklinGothicMedium_13.rdf

#define FranklinGothicMedium_13_NUM_RESOURCES 2UL

#define FranklinGothicMedium_13_Font_OFFSET 0UL
#define FranklinGothicMedium_13_FontData_OFFSET 20UL
