// Automatically generated by the bundler tool from FranklinGothicMedium_12.rdf

#define FranklinGothicMedium_12_NUM_RESOURCES 2UL

#define FranklinGothicMedium_12_Font_OFFSET 0UL
#define FranklinGothicMedium_12_FontData_OFFSET 20UL
